name: quantum-computing
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11

  # Core quantum computing
  - pip

  # Scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0

  # Visualisation
  - matplotlib>=3.7.0
  - plotly>=5.17.0

  # Interactive notebooks
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - ipywidgets>=8.0.0

  # Development tools
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0

  # Utilities
  - pandas>=2.0.0
  - tqdm>=4.65.0

  # Pip-only packages (not available via conda)
  - pip:
      - qiskit>=1.0.0
      - qiskit-aer>=0.13.0
      - qiskit-ibm-runtime>=0.18.0
      - qiskit-visualization>=0.7.0
      - streamlit>=1.28.0
      - pytest-cov>=4.1.0